# # # # # # # # # # # # # # # # # # # 
#                                   # 
#   This is an auto-generated file  # 
#   based on the jupyter notebook   # 
#
#   >   ``01 - HouseExpo Data.ipynb''
#
#                                   #
# # # # # # # # # # # # # # # # # # #

push!(LOAD_PATH, "../src");
include("../../src/pose.jl"); # autogenerated from: "../src/pose.jl"
import JSON
using StatsBase: mean
using Geometry: bounding_box, Segment, segments
using MyUtils: summarize_vars
using Colors, Plots
col = palette(:default);

fname = "../data/task_inputs/example_1.json"
d = JSON.parsefile(fname)

verts    = Vector{Vector{Float64}}(d["verts"]);
clutter  = Vector{Vector{Vector{Float64}}}(d["clutter_verts"]);
paths  = Vector{Vector{Vector{Float64}}}(d["paths"]);

_segs   = segments(verts);
_boxes  = vcat(segments.(clutter)...);
_bb     = bounding_box(_segs)
_center = mean(_bb);

# Choose path
i = 3
xs = paths[i]

# Unpack path into
# poses and controls
_dxs  = xs[2:end] - xs[1:end-1]
_hds  = angle.(_dxs)
_dhds = _hds[2:end] - _hds[1:end-1];
_xs = xs[1:end-2];

_ps = [Pose(x,hd) for (x,hd) in zip(_xs, _hds)];
_us = [Control(dx,dhd) for (dx,dhd) in zip(_dxs, _dhds)]
_T  = length(_xs);

println("Loading data from `$(fname)`, and\npopulating Main namespace with variables:\n")
summarize_vars(:(_segs, _boxes, _center, _xs, _hds, _ps, _dxs, _dhds, _us, _T))
