# # # # # # # # # # # # # # # # # # # 
#                                   # 
#   This is an auto-generated file  # 
#   based on the jupyter notebook   # 
#
#   >   ``20 - Localization Module.ipynb''
#
#                                   #
# # # # # # # # # # # # # # # # # # #

##################################### 
module Localization  
#####################################


using BenchmarkTools;
using CUDA
using LaTeXStrings
using Colors, Plots, Images;
col = palette(:default);
(cgrad::PlotUtils.ContinuousColorGradient)(xs::Vector{Vector{Float64}}) = [cgrad[x] for x in xs];
(cgrad::PlotUtils.ContinuousColorGradient)(m::Matrix{Float64}) = reshape(cgrad[m[:]], size(m));
using Gen
using Fmt: @f_str, format # Python-style f-strings
using StatsBase: mean
using Random: shuffle, randperm

using MyUtils
using MyCudaUtils
using Geometry: Segment
include("../../src/pose.jl"); # autogenerated from: "../src/pose.jl"
using GenDistributionZoo: ProductDistribution, diagnormal
mvuniform = ProductDistribution(uniform);
include("../../src/cuda_raycaster_line_map_b.jl"); # autogenerated from: "../src/cuda_raycaster_line_map_b.jl"
include("../../v2/src/sensor_distribution.jl"); # autogenerated from: "../v2/src/sensor_distribution.jl"

#####################################
end  
#####################################
